/**
 * Code generated by ISC
 * ISC Version: v1.0.0
 * Do not edit this file manually!
 * This code will be regenerated on every change
 */
// Import param handler module
const {
  params,
  instanceApi
} = require('@lwr-lara/isc-instance-api');

class SonyEmulator {
  constructor() {
    this.instance = instanceApi.getSelf();

    /* Registering events */
    this.instance.registerEvent('controlButtonClicked', async () => {}, async () => {});
    this.instance.registerEvent('muteStatusChanged', async () => {}, async () => {});
    this.instance.registerEvent('powerStatusChanged', async () => {}, async () => {});

    /* Registering events end */

    /* Registering methods */
    this.instance.registerMethod('setMuteState', this.setMuteState.bind(this));
    this.instance.registerMethod('setPowerState', this.setPowerState.bind(this));

    /* Registering methods end */

    this.init();

    /* Rules */
    // Set actions for rules
    instanceApi.ruleManager.init();
    instanceApi.ruleManager.setAction('react to muteStatusChange', async (status) => {
      // Execute actions
      /* Action code */
      try {
        if (status == "Muted") {
          this.instance.addClass("muteButton", `selected`, this.instance.instanceId);
          this.instance.removeClass("muteButton", `deselected`, this.instance.instanceId);
        } else {
          this.instance.addClass("muteButton", `deselected`, this.instance.instanceId);
          this.instance.removeClass("muteButton", `selected`, this.instance.instanceId);
        }

      } catch (e) {
        console.error("Error occurred during execution of action code in rule 'react to muteStatusChange'");
        if (e && e.message) {
          console.error(e.message);
        }
      }
      /* Action code end */
    })
    instanceApi.ruleManager.setAction('react to powerStatusChange', async (status) => {
      // Execute actions
      /* Action code */
      try {
        if (status == "On") {
          this.instance.addClass("powerButton", `selected`, this.instance.instanceId);
          this.instance.removeClass("powerButton", `deselected`, this.instance.instanceId);
        } else {
          this.instance.addClass("powerButton", `deselected`, this.instance.instanceId);
          this.instance.removeClass("powerButton", `selected`, this.instance.instanceId);
        }

      } catch (e) {
        console.error("Error occurred during execution of action code in rule 'react to powerStatusChange'");
        if (e && e.message) {
          console.error(e.message);
        }
      }
      /* Action code end */
    })
    instanceApi.ruleManager.setAction('react to button click', async (buttonId) => {
      // Execute actions
      /* Action code */
      try {
        console.log("Button clicked: " + buttonId);

        if (buttonId == "powerButton") {
          const currValue = await this.instance.variables[`powerStatus`].value;
          const newValue = currValue == "On" ? "Off" : "On";
          await this.instance.setPowerState(newValue);
        }


        if (buttonId == "muteButton") {
          const currValue = await this.instance.variables[`muteStatus`].value;
          const newValue = currValue == "Muted" ? "Unmuted" : "Muted";
          await this.instance.setMuteState(newValue);
        }


      } catch (e) {
        console.error("Error occurred during execution of action code in rule 'react to button click'");
        if (e && e.message) {
          console.error(e.message);
        }
      }
      /* Action code end */
    })
    instanceApi.ruleManager.setAction('muteStatusChanged', async (status) => {
      // Execute actions
      /* Action code */
      try {
        console.log("Mute Status changed to " + status);
      } catch (e) {
        console.error("Error occurred during execution of action code in rule 'muteStatusChanged'");
        if (e && e.message) {
          console.error(e.message);
        }
      }
      /* Action code end */
    })
    instanceApi.ruleManager.setAction('powerStatusChanged', async (status) => {
      // Execute actions
      /* Action code */
      try {
        console.log("Power Status changed to " + status);
      } catch (e) {
        console.error("Error occurred during execution of action code in rule 'powerStatusChanged'");
        if (e && e.message) {
          console.error(e.message);
        }
      }
      /* Action code end */
    })

    /* Rules end */
  }

  async init() {
    /* beautify ignore:start */
        /* Custom user code */
        // Import required modules

        const net = require('net'); 
        const os = require('os');
        const { BraviaEmulator } = require('./bravia-emulator.js');
        const { SSIP, parsePacket } = require('./ssip-protocol.js');

      // Initialize emulator with LARA event emitter
        this.emulator = new BraviaEmulator((eventName, data) => {
          // Dispatch LARA events when emulator state changes
          this.instance.dispatchEvent(eventName, data);

          // Update LARA properties and the board
          updateStatusBoard();
        });

        this.server = null;
        this.port = params.port || 20060;

        // Color codes for status board
        this.colorCodes = {
          success: "#08d15d",   // Green for active/on states
          warning: "#f90",      // Orange for warning states
          error: "#e74747",     // Red for error/off states
          info: "#2196F3"       // Blue for info states
        };
            
        /**
           * Get network IP addresses
           */
        const getNetworkAddresses = () => {
            const interfaces = os.networkInterfaces();
            const addresses = [];
        
            for (const name of Object.keys(interfaces)) {
              for (const iface of interfaces[name]) {
                // Skip internal and non-IPv4 addresses
                if (iface.family === 'IPv4' && !iface.internal) {
                  addresses.push(iface.address);
                }
              }
            }
        
            return addresses;
          }
        

          /**
       * Handle TCP client connection
       */
      const handleConnection = (socket) => {
        const clientId = `${socket.remoteAddress}:${socket.remotePort}`;
        console.log(`[Server] Client connected: ${clientId}`);

        // Add client to emulator's client set
        this.emulator.addClient(socket);

        // Update connected clients count
        this.instance.variables["connectedClients"].value = this.emulator.clients.size;
        this.instance.updateStatus("Connected Clients", this.emulator.clients.size.toString(), {
          color: this.emulator.clients.size > 0 ? this.colorCodes.success : this.colorCodes.warning
        });

        // Buffer for accumulating incoming data
        let buffer = Buffer.alloc(0);

        socket.on('data', (data) => {
          // Accumulate data
          buffer = Buffer.concat([buffer, data]);

          // Process complete 24-byte packets
          while (buffer.length >= SSIP.PACKET_SIZE) {
            const packet = buffer.slice(0, SSIP.PACKET_SIZE);
            buffer = buffer.slice(SSIP.PACKET_SIZE);

            // Handle packet and send response
            const response = this.emulator.handlePacket(packet);
            if (response) {
              socket.write(response);
            }
          }
        });

        socket.on('end', () => {
          console.log(`[Server] Client disconnected: ${clientId}`);
          this.emulator.removeClient(socket);

          // Update connected clients count
          this.instance.variables["connectedClients"].value = this.emulator.clients.size;
          this.instance.updateStatus("Connected Clients", this.emulator.clients.size.toString(), {
            color: this.emulator.clients.size > 0 ? this.colorCodes.success : this.colorCodes.warning
          });
        });

        socket.on('error', (err) => {
          console.error(`[Server] Socket error (${clientId}):`, err.message);
          this.emulator.removeClient(socket);

          // Update connected clients count
          this.instance.variables["connectedClients"].value = this.emulator.clients.size;
          this.instance.updateStatus("Connected Clients", this.emulator.clients.size.toString(), {
            color: this.emulator.clients.size > 0 ? this.colorCodes.success : this.colorCodes.warning
          });
        });
      }

      
      /**
       * Initialize status board with default values
       */
      const initializeStatusBoard = () => {
        this.instance.updateStatus("Server Status", "Initializing...", {
          color: this.colorCodes.warning
        });
        this.instance.updateStatus("Connected Clients", "0", {
          color: this.colorCodes.warning
        });
        this.instance.updateStatus("Power", "Off", {
          color: this.colorCodes.error
        });
        this.instance.updateStatus("Volume", "15", {
          color: this.colorCodes.info
        });
        this.instance.updateStatus("Mute", "Unmuted", {
          color: this.colorCodes.success
        });
        this.instance.updateStatus("Input", "HDMI 1", {
          color: this.colorCodes.info
        });
        this.instance.updateStatus("Scene", "general", {
          color: this.colorCodes.info
        });
      }

      /**
       * Update status board with current emulator state
       */
      const updateStatusBoard = () => {
        const state = this.emulator.getState();

        // Update status variables
        const powerStatus = state.power === 1 ? "On" : "Off";
        const muteStatus = state.mute === 1 ? "Muted" : "Unmuted";
        const inputTypes = { 1: 'HDMI', 3: 'Composite', 4: 'Component', 5: 'Screen Mirroring' };
        const inputSource = `${inputTypes[state.input.type] || 'Unknown'} ${state.input.number}`;

        this.instance.variables["powerStatus"].value = powerStatus;
        this.instance.variables["volumeLevel"].value = state.volume;
        this.instance.variables["muteStatus"].value = muteStatus;
        this.instance.variables["inputSource"].value = inputSource;
        this.instance.variables["sceneMode"].value = state.scene;

        // Update status board display
        this.instance.updateStatus("Power", powerStatus, {
          color: state.power === 1 ? this.colorCodes.success : this.colorCodes.error
        });

        this.instance.updateStatus("Volume", state.volume.toString(), {
          color: this.colorCodes.info
        });

        this.instance.updateStatus("Mute", muteStatus, {
          color: this.colorCodes.success
        });

        this.instance.updateStatus("Input", inputSource, {
          color: this.colorCodes.info
        });

        this.instance.updateStatus("Scene", state.scene, {
          color: this.colorCodes.info
        });
      }

      /**
       * Print current device state
       */
      const printState = () => {
        const state = this.emulator.getState();
        console.log('Device State:');
        console.log(`  Power:  ${state.power ? 'On' : 'Off'}`);
        console.log(`  Volume: ${state.volume} (${state.mute ? 'Muted' : 'Unmuted'})`);

        const inputTypes = { 1: 'HDMI', 3: 'Composite', 4: 'Component', 5: 'Screen Mirroring' };
        console.log(`  Input:  ${inputTypes[state.input.type]} ${state.input.number}`);
        console.log(`  Scene:  ${state.scene}`);
        console.log('');
      }

            console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log('  Sony Bravia SSIP Emulator - LARA Driver');
        console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log(`  Starting TCP server on port ${this.port}...`);

        // Initialize status board
        initializeStatusBoard();

        // Create TCP server
        this.server = net.createServer((socket) => handleConnection(socket));

        this.server.on('error', (err) => {
          console.error('[Server] Error:', err.message);
          if (err.code === 'EADDRINUSE') {
            console.error(`[Server] Port ${this.port} is already in use`);
          }
        });

        this.server.on('listening', () => {
          const addresses = getNetworkAddresses();

          console.log(`[Server] Port: ${this.port}`);
          console.log(`[Server] Protocol: SSIP (Simple Single-wire IP)`);
          console.log('');
          console.log('  Network Addresses:');
          console.log(`    localhost:${this.port}`);
          console.log(`    127.0.0.1:${this.port}`);
          if (addresses.length > 0) {
            addresses.forEach(addr => {
              console.log(`    ${addr}:${this.port}`);
            });
          }
          console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
          console.log('');
          printState();

          // Update server running status
          this.instance.variables["serverRunning"].value = true;
          this.instance.updateStatus("Server Status", "Running", {
            color: this.colorCodes.success
          });
          updateStatusBoard();
        });

        // Start listening
        this.server.listen(this.port, '0.0.0.0');

        updateStatusBoard();
        /* Custom user code end */
        /* beautify ignore:end */
  }

  /* Methods */
  /**
   * @method setMuteState
   * @param {string} state
   * @returns {void}
   * @description {}
   */
  async setMuteState(state) {
    const value = (state == "Muted") ? 1 : 0;
    this.emulator.setAudioMute(value);
    this.instance.variables["muteStatus"].value = state;
    this.instance.updateStatus("Mute", state, {
      color: this.colorCodes.success
    });
  }
  /**
   * @method setPowerState
   * @param {string} state
   * @returns {void}
   * @description {}
   */
  async setPowerState(state) {
    const value = (state == "On") ? 1 : 0;
    this.emulator.setPowerStatus(value);
    this.instance.variables["powerStatus"].value = state;
    this.instance.updateStatus("Power", state, {
      color: value === 1 ? this.colorCodes.success : this.colorCodes.error
    });
  }

  /* Methods end */

}

const SonyEmulatorInstance = new SonyEmulator();